name: guruji_gururaja
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^16.2.0
  material_design_icons_flutter: ^7.0.7296
  shared_preferences: ^2.5.3
  http: ^1.5.0
  url_launcher: ^6.3.2
  equatable: ^2.0.7
  share_plus: ^11.1.0
  flutter_html: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true

  # Use your 1024×1024 square photo as the source
  image_path: "assets/images/icon.jpg"

  # ✅ Adaptive icon (Android)
  adaptive_icon_foreground: "assets/images/icon.jpg"
  adaptive_icon_background: "#222222"   # dark grey to match your photo background

  # iOS best-practice
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/img.png
    - assets/images/face.png
    - assets/images/splash.jpg
    - assets/images/about_face.jpg
    - assets/images/header.PNG
    - assets/images/icon.jpg
    - assets/stones/

    - assets/palan/palan_ta.json
    - assets/names/natchathiram_names_ta.json

    - assets/tarot/
    - assets/tarot/data/tarot_cards.json







